tests(PythonQtTestCleanup): Fix unknown attribute in testCallQtMethodInDel
This change ensures that the `QTimer` object is properly deleted to avoid the
AttributeError when the `__del__` method is called.

Fixes the following error:

```
Exception ignored in: <function TimerWrapper.__del__ at 0x510000073760>
Traceback (most recent call last):
  File "<string>", line 6, in __del__
AttributeError: 'QTimer' object has no attribute 'setSingleShot'
```