BUG: Unsupported combination headers caused build error
qprintengine.h:12:1: error: explicit specialization of
   'QMetaTypeId<QMarginsF>' after instantiation